sudo: false
language: generic
matrix:
  include:
    -
      env: PROJECT=apps/ethvm
      language: node_js
      node_js:
        - "10"
    -
      env: PROJECT=apps/ethvm-e2etest
      language: node_js
      node_js:
        - "10"
    -
      env: PROJECT=apps/ethvm-unittest
      language: node_js
      node_js:
        - "10"
    -
      env: PROJECT=apps/server
      language: node_js
      node_js:
        - "10"

before_install:
  - 'if [ $PROJECT = "apps/ethvm" ]; then cd $TRAVIS_BUILD_DIR/apps/ethvm; fi'
  - 'if [ $PROJECT = "apps/server" ]; then cd $TRAVIS_BUILD_DIR/apps/server; fi'
  - 'if [ $PROJECT = "=apps/ethvm-e2etest" ]; then cd $TRAVIS_BUILD_DIR/apps/server; fi'
  - 'if [ $PROJECT = "=apps/ethvm-unittest" ]; then cd $TRAVIS_BUILD_DIR/apps/server; fi'



install:
  - yarn install

before_script:
  - 'if [ $PROJECT = "apps/ethvm" ]; then cd $TRAVIS_BUILD_DIR/apps/ethvm; fi'
  - 'if [ $PROJECT = "apps/server" ]; then cd $TRAVIS_BUILD_DIR/apps/server; fi'
  - 'if [ $PROJECT = "apps/ethvm-unittest" ]; then cd $TRAVIS_BUILD_DIR/apps/server; fi'


script:
  - 'if [ $PROJECT = "apps/server" ]; then yarn lint;  fi'
  - 'if [ $PROJECT = "=apps/ethvm-e2etest" ]; then yarn test:e2e --runInBand; fi'
  - 'if [ $PROJECT = "apps/ethvm-unittest" ];then  yarn test:unit; fi'

