sudo: true
language: generic
services:
  - redis-server
  - docker
git:
  submodules:
    false
matrix:
  include:
    -
      env:
        - ID=apps/server
        - PROJECT_DIR=$TRAVIS_BUILD_DIR/apps/server
        - INSTALL='yarn install'
        - ACTION='yarn lint'
      language: node_js
      node_js:
        - "10"
    -
      env:
        - ID=apps/server-unit-test
        - PROJECT_DIR=$TRAVIS_BUILD_DIR/apps/server
        - INSTALL='yarn install'
        - ACTION='yarn test:unit'
      language: node_js
      node_js:
        - "10"
    -
      env:
        - ID=apps/server-e2e-test
        - PROJECT_DIR=$TRAVIS_BUILD_DIR/apps/server
        - INSTALL='yarn install'
        - ACTION='yarn test:e2e'
      language: node_js
      node_js:
        - "10"
    -
      env:
        - ID=apps/bolt
        - PROJECT_DIR=$TRAVIS_BUILD_DIR/apps/bolt
        - INSTALL=''
        - ACTION='./gradlew --no-daemon test'
      language: generic

before_install:
  - ./.travis/before-install.sh

install:
  - cd $PROJECT_DIR
  - eval $INSTALL

script:
  - cd $PROJECT_DIR
  - eval $ACTION

deploy:
  provider: script
  script: bash ./.travis/docker_push.sh
  on:
    branch: master
