language: generic
matrix:
  include:
    -
      env: PROJECT=apps/ethvm
      language: node_js
      node_js:
        - "9"
        - "10"
    -
      env: PROJECT=apps/server

sudo: false

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.7.0
  - export PATH=$HOME/.yarn/bin:$PATH
install:
  - yarn install
before_script:
  - 'if [ $PROJECT = "apps/ethvm" ]; cd apps/ethvm fi'
  - 'if [ $PROJECT = "apps/server" ]; cd apps/server fi'


script:
  - 'if [ $PROJECT = "apps/ethvm" ]; yarn lint fi'
  - 'if [ $PROJECT = "apps/server" ]; yarn test:unit fi'
